#!/bin/bash
# Scheduled story release: FB + IG (release_social.py), then Nostr (post_nostr.py)
# and X (x_tease.py). Nostr + X only run if the FB+IG step succeeded (never post
# Nostr/X before the story is live on FB).
# X tease is auto-generated by the local Gemma model (no human approval) per the
# 2026-06-28 rule change — the model picks the best teaser following the X craft
# rules (no punchline reveal, opposite emotional direction).
# Usage: scheduled_release.sh <SID> "<theme hashtags>"
set -uo pipefail
SID="${1:?usage: scheduled_release.sh HC### \"#tags\"}"
THEME="${2:-}"
VENV=/Users/rmello/holy-chip/venv/nostr/bin/python
cd /Users/rmello/holy-chip || exit 1

echo "--- $SID: FB + IG ---"
python3 tools/release_social.py "$SID" "$THEME"
RC=$?

if [ $RC -eq 0 ]; then
  echo "--- $SID: Nostr ---"
  "$VENV" tools/post_nostr.py --story "$SID"
  echo "--- $SID: X ---"
  python3 tools/x_tease.py "$SID" "$THEME"
else
  echo "release_social failed (rc=$RC) — skipping Nostr + X"
fi
exit $RC
