#!/usr/bin/env python3
"""Promo photo: the real cover, in perspective, on the blank book photo.

The scene (blank.jpg) was generated by Gemini with a BLANK cover, because when
Gemini drew the cover itself it changed the bot, bent the subtitle and invented
spine text. Here the exact cover is warped onto the board and lit by the photo:
every pixel is the cover colour scaled by how the blank board was lit, so the
light falloff and the linen texture carry over.

    python promo_mockup.py   (needs numpy)  -> build/proto/book_promo.jpg
"""
from pathlib import Path
import numpy as np
from PIL import Image, ImageFilter

D = Path(__file__).parent / "build" / "proto"
QUAD = [(62, 958), (1015, 512), (1820, 1235), (835, 1812)]   # cover TL, TR, BR, BL in blank.jpg
PAPER = np.array([0xF6, 0xF3, 0xEA], float)                    # the cover's own background


def coeffs(dst, src):
    A, B = [], []
    for (x, y), (u, v) in zip(dst, src):
        A.append([x, y, 1, 0, 0, 0, -u * x, -u * y]); B.append(u)
        A.append([0, 0, 0, x, y, 1, -v * x, -v * y]); B.append(v)
    return np.linalg.solve(np.array(A, float), np.array(B, float)).tolist()


def main():
    photo = Image.open(Path(__file__).parent / "assets" / "promo" / "blank.jpg").convert("RGB"); W, H = photo.size
    cover = Image.open(D / "cover_hi.png").convert("RGB"); S = cover.size[0]
    cx = sum(p[0] for p in QUAD) / 4; cy = sum(p[1] for p in QUAD) / 4
    quad = [(x + (cx - x) * 0.012, y + (cy - y) * 0.012) for x, y in QUAD]   # off the rounded edge
    c = coeffs(quad, [(0, 0), (S, 0), (S, S), (0, S)])
    warp = cover.transform((W, H), Image.PERSPECTIVE, c, Image.BICUBIC)
    mask = Image.new("L", (S, S), 255).transform((W, H), Image.PERSPECTIVE, c, Image.BICUBIC)
    mask = mask.filter(ImageFilter.GaussianBlur(0.8))
    P = np.asarray(photo, float); C = np.asarray(warp, float)
    M = np.asarray(mask, float)[..., None] / 255
    ref = np.median(P[np.asarray(mask) > 250], axis=0)      # the blank board's colour
    out = P * (1 - M) + np.clip(C / PAPER * P, 0, 255) * M  # cover x photo lighting
    Image.fromarray(out.astype(np.uint8)).save(D / "book_promo.jpg", quality=94)
    print(D / "book_promo.jpg", "board", ref.round())


if __name__ == "__main__":
    main()
